[phases.setup]
aptPkgs = ["ffmpeg", "espeak-ng", "libespeak-ng1", "espeak-ng-data"]

[phases.install]
cmds = [
  # pyttsx3 بعضی وقت‌ها فقط به دنبال 'espeak' می‌گردد
  "ln -sf /usr/bin/espeak-ng /usr/bin/espeak || true"
]

[phases.start]
# اگر لازم شد مسیر دیتا را هم ست کن (مسیر پیش‌فرض Debian):
cmd = "ESPEAK_DATA_PATH=/usr/lib/x86_64-linux-gnu/espeak-ng-data uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000}"
